/**
 * Generates the docs' dark palette from the TUI's.
 *
 * The docs and the terminal show the same thing — a diff, a tool call, an error
 * — and they have to show it in the same colours, or a reader comparing the page
 * to their own terminal sees two different products. Hand-copying the hex values
 * guarantees they drift, so the dark half of `tokens.css` is generated from
 * `tui/src/styles/theme.ts` instead.
 *
 *   bun run docs:tokens
 *
 * Writes `site/src/docs/tokens.generated.css`, which `tokens.css` imports. The
 * light half is authored by hand: it descends from the landing page, not from
 * the terminal.
 */

import { colors, markdownColors } from "../../tui/src/styles/theme";

/**
 * Docs token → the `theme.ts` colour it takes. Only the tokens whose value the
 * terminal is authoritative for: the surfaces code sits on, the text on them,
 * and every syntax and diff colour. Layout tokens (measure, spacing, radii) are
 * not colours and stay in the authored file.
 */
const DARK: Array<[token: string, value: string, note?: string]> = [
  // Surfaces. `--doc-bg` is the page ground; in light mode that is the landing
  // page's lavender, and in dark it is the terminal's own background.
  ["--doc-bg", colors.bgBase],
  ["--doc-surface", "#0d0d0d", "the landing page's --bg, one step off bgBase"],
  ["--doc-raised", colors.bgLayer01, "code blocks, cards, table headers"],
  ["--doc-sunken", colors.bgLayer02],

  // Text.
  ["--doc-text", colors.textBase],
  ["--doc-text-2", colors.textMuted],
  ["--doc-faint", colors.textFaint],
  ["--doc-strong", colors.textStrong],

  // Lines. `borderMuted` rather than `borderBase`: a hairline that reads
  // correctly around a terminal box is too loud around a paragraph.
  ["--doc-line", colors.borderMuted],
  ["--doc-line-2", colors.borderBase],

  // Accent. The TUI's periwinkle, not the web violet — in dark mode the page is
  // the terminal's background, so it takes the terminal's accent.
  ["--doc-accent", colors.primary],
  ["--doc-accent-quiet", colors.secondary],

  // Callout states, mapped to the TUI's state colours so a warning in the docs
  // is the same yellow as a warning in the product.
  ["--doc-note", colors.borderBase],
  ["--doc-tip", colors.primary],
  ["--doc-warning", colors.warningBase],
  ["--doc-danger", colors.dangerBase],

  // Diff. Bands are tints, not text colours — syntax highlighting sits on top.
  ["--doc-diff-add", colors.diffAdd],
  ["--doc-diff-remove", colors.diffRemove],
  ["--doc-diff-add-bg", colors.diffAddBg],
  ["--doc-diff-remove-bg", colors.diffRemoveBg],

  // Syntax, from the markdown palette the TUI renders assistant prose with.
  ["--doc-code-text", markdownColors.text],
  ["--doc-code-heading", markdownColors.heading],
  ["--doc-code-string", markdownColors.code],
  ["--doc-code-keyword", markdownColors.strong],
  ["--doc-code-comment", colors.textFaint],
  ["--doc-code-link", markdownColors.link],
];

function declarations(indent: string): string {
  return DARK.map(([token, value, note]) => {
    const line = `${indent}${token}: ${value};`;
    return note ? `${line} /* ${note} */` : line;
  }).join("\n");
}

const output = `/* Generated by site/scripts/generate-tokens.ts — do not edit.
 *
 * The dark palette, taken from tui/src/styles/theme.ts so the docs and the
 * terminal cannot disagree about what a diff or a warning looks like.
 *
 * Regenerate with:  bun run docs:tokens
 */

@media (prefers-color-scheme: dark) {
  :root {
${declarations("    ")}
  }
}

/* The toggle has to win in both directions: a reader who forces dark inside a
   light OS gets dark, and one who forces light inside a dark OS gets the
   authored light values back (tokens.css re-states those under [data-theme="light"]). */
:root[data-theme="dark"] {
${declarations("  ")}
}
`;

const target = new URL("../src/docs/tokens.generated.css", import.meta.url);
await Bun.write(target, output);

console.log(
  `Wrote ${DARK.length} dark tokens → site/src/docs/tokens.generated.css`,
);
